### ISSUE TITLE
Parametrized tests?

### ISSUE THREAD

**Issue by ahirner** [charles-r-earp/autograph#43]
I was checking out `cargo test` on metal and all non-f64 tests pass 🎉 

Going forward, I think tests parametrized on `dtype` and `Device` (include/exclude via test params?) would make for a DRY yet granular foundation. I'm no expert in rust fixtures, but saw [rstest](https://github.com/la10736/rstest) and macro approaches.

Do you have any opinion on that?

**Comment by charles-r-earp** [comment]
Having trouble on windows ci with f64 as well. I'm developing on Ubuntu and that works fine. 

For machine learning, I don't plan to use f64 but I thought it would be useful for general purpose computation. I was hoping to support 16 bit floats as well at some point, particularly bf16.

I thought about using macros to define the tests separately per type, that makes sense, I just neglected that for simplicity.

The main issue is that the tests should all pass, or fail. I'm not thrilled to have only partial support for certain things. Unless there's a fix I may decide to remove f64 for now.
