### ISSUE TITLE
Add `candle` to benchmarks

### ISSUE THREAD

**Issue by LegNeato** [charles-r-earp/autograph#67]
It would be good to have [`candle`](https://github.com/huggingface/candle) added to the benchmarks. It looks to have a mnist training example: https://github.com/huggingface/candle/blob/main/candle-examples/examples/mnist-training/main.rs. I'm happy to put up a PR, though I have never done any ML so will need a lot of mentoring.

**Comment by charles-r-earp** [comment]
Agreed on adding candle benchmarks.

Unfortunately autograph and krnl are locked to half 2.1.0, incompatible with candle (which requires 2.3.1). Once that's fixed I might take a stab at it.

**Comment by LegNeato** [comment]
You could temporarily use `package=myhalf` so they don't conflict if you wanted...not sure it is worth it through.
